name: autoroute
description: Smart Auto Driver App for Route Matching & Ride Pickup
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  
  # Google Maps & Location
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_places_flutter: ^2.0.6
  
  # UI & Navigation
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  
  # HTTP & Networking
  http: ^1.1.2
  dio: ^5.4.0
  
  # Utilities
  intl: ^0.19.0
  image_picker: ^1.0.5
  permission_handler: ^11.1.0
  flutter_local_notifications: ^16.3.0
  
  # AI & Voice (Optional)
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700